services:
  auth-service:
    container_name: auth-service
    build: .
    depends_on:
      - db
    user: "${APP_UID}:${APP_GID}"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  db:
    container_name: auth-service-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
