services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    depends_on:
      - db
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: niki.ponce@gmail.com
      PGADMIN_DEFAULT_PASSWORD: djasoieoqweaujspa
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  auth-service:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
  pgadmin-data:
