services:
  auth-service:
    container_name: auth-service
    build: .
    depends_on:
      - db
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY:-secretkey123456789}
      - VIRTUAL_HOST=${{ vars.VIRTUAL_HOST }}
      - VIRTUAL_PORT=${{ vars.VIRTUAL_PORT }}
    volumes:
      - .:/app
    networks:
      - proxy
  db:
    container_name: authify-db
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - proxy
volumes:
  postgres_data:

networks:
  proxy:
    external: true
