services:
  db:
    image: postgres:15
    container_name: auth-service-db
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    depends_on:
      - db
    ports:
      - "8888:80"
    env_file: .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  auth-service:
    build: .
    depends_on:
      - db
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
  pgadmin-data:
